# Generated by Django 3.1.12 on 2021-12-11 11:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('account_no', models.CharField(max_length=400)),
                ('opening_Balance', models.FloatField()),
                ('current_Balance', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CashHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('opening_Balance', models.FloatField()),
                ('current_Balance', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=300000, null=True)),
                ('transaction_type', models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], max_length=50)),
                ('total_amount', models.FloatField(null=True)),
                ('net_balance', models.FloatField(blank=True, default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('cnic', models.CharField(blank=True, max_length=20, null=True)),
                ('contact', models.CharField(blank=True, max_length=11, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particular', models.CharField(max_length=300, unique=True)),
                ('model_no', models.CharField(max_length=100)),
                ('capasity', models.IntegerField()),
                ('unit', models.CharField(max_length=300)),
                ('cost_price', models.IntegerField()),
                ('sale_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField()),
                ('transaction_type', models.CharField(choices=[('Bank', 'Bank'), ('Cash', 'Cash')], max_length=5)),
                ('description', models.TextField(blank=True, default='Not Set')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Arrived', 'Arrived')], max_length=20)),
                ('qty_remaining', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sales_Officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('cnic', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=11)),
                ('commision', models.FloatField()),
                ('address', models.CharField(max_length=1000)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesOfficer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('commission', models.FloatField(default=0.0)),
                ('contact', models.CharField(max_length=13)),
                ('opening_Balance', models.FloatField()),
                ('current_Balance', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Vender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('contact', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankLedger',
            fields=[
                ('ledger_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='POS_APP.ledger')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POS_APP.bank')),
            ],
            bases=('POS_APP.ledger',),
        ),
        migrations.CreateModel(
            name='CashLedger',
            fields=[
                ('ledger_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='POS_APP.ledger')),
                ('cash_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POS_APP.cashhead')),
            ],
            bases=('POS_APP.ledger',),
        ),
        migrations.CreateModel(
            name='PurchaseProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POS_APP.product')),
                ('purchas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POS_APP.purchase')),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='sales_officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POS_APP.sales_officer'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='vender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POS_APP.vender'),
        ),
        migrations.CreateModel(
            name='VenderLedger',
            fields=[
                ('ledger_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='POS_APP.ledger')),
                ('purchases', models.IntegerField(blank=True, null=True)),
                ('sales_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POS_APP.vender')),
            ],
            bases=('POS_APP.ledger',),
        ),
        migrations.CreateModel(
            name='SalesOfficerLedger',
            fields=[
                ('ledger_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='POS_APP.ledger')),
                ('party_order', models.IntegerField(blank=True, null=True)),
                ('sales_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POS_APP.salesofficer')),
            ],
            bases=('POS_APP.ledger',),
        ),
        migrations.AddField(
            model_name='purchase',
            name='bl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POS_APP.bankledger'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='cl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POS_APP.cashledger'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='vl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POS_APP.venderledger'),
        ),
        migrations.CreateModel(
            name='PartyLedger',
            fields=[
                ('ledger_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='POS_APP.ledger')),
                ('freight', models.FloatField(blank=True, null=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POS_APP.party')),
                ('sales_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='POS_APP.salesofficer')),
            ],
            bases=('POS_APP.ledger',),
        ),
    ]
