# Generated by Django 3.1.12 on 2021-12-11 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POS_APP', '0002_auto_20211211_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='sales_officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POS_APP.salesofficer'),
        ),
        migrations.DeleteModel(
            name='Sales_Officer',
        ),
    ]
