# Generated by Django 3.1.12 on 2021-12-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS_APP', '0003_auto_20211211_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
