# Generated by Django 3.1.12 on 2021-12-12 13:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('POS_APP', '0004_auto_20211212_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
