# Generated by Django 3.1.12 on 2021-12-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS_APP', '0005_product_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default='40 MG', max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='capasity',
            field=models.IntegerField(blank=True),
        ),
    ]
