# Generated by Django 3.1.12 on 2022-01-01 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POS_APP', '0008_remove_purchase_sales_officer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='bl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='POS_APP.bankledger'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='cl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='POS_APP.cashledger'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Arrived', 'Arrived')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='vl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='POS_APP.venderledger'),
        ),
    ]
