# Generated by Django 3.1.12 on 2022-01-01 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POS_APP', '0009_auto_20220101_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='POS_APP.bank'),
        ),
    ]
