# Generated by Django 3.1.12 on 2022-01-15 14:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('POS_APP', '0011_purchase_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unloading', models.FloatField(blank=True, null=True)),
                ('freight', models.FloatField(blank=True, null=True)),
                ('total_amount', models.FloatField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered')], default='Pending', max_length=20)),
                ('transaction_type', models.CharField(choices=[('Bank', 'Bank'), ('Cash', 'Cash')], max_length=5)),
                ('description', models.TextField(blank=True, default='Not Set')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='POS_APP.bank')),
                ('bl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='POS_APP.bankledger')),
                ('cl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='POS_APP.cashledger')),
                ('ll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='POS_APP.partyledger')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POS_APP.party')),
                ('salesOfficer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='POS_APP.salesofficer')),
            ],
        ),
        migrations.CreateModel(
            name='SalesProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POS_APP.product')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POS_APP.sales')),
            ],
        ),
    ]
